# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKnmDhcYd1B0k20_ctBRG6dlOq-LEt2b
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("model.pkl")
st.title("California Home Price Predictor")

sqft = st.number_input("Living Area (sqft)", 500, 10000, step=50)
beds = st.number_input("Bedrooms", 0, 10)
baths = st.number_input("Bathrooms", 0, 10)
zip_code = st.text_input("ZIP Code", "90210")
year_built = st.number_input("Year Built", 1900, 2025)

if st.button("Predict Price"):
    input_df = pd.DataFrame({
        "LivingArea": [sqft],
        "BedroomsTotal": [beds],
        "BathroomsTotalInteger": [baths],
        "ZipCodeGroup": [zip_code],
        "BuildingAge": [2025 - year_built]
    })
    prediction = model.predict(input_df)[0]
    st.success(f"Estimated Home Price: ${prediction:,.0f}")

!pip install streamlit pyngrok

